/*
 * generated by Xtext
 */
package at.bestsolution.objc.mapper.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractMapperValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(at.bestsolution.objc.mapper.mapper.MapperPackage.eINSTANCE);
		return result;
	}
}
