/*
* generated by Xtext
*/
package at.bestsolution.objc.mapper.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.bestsolution.objc.mapper.services.MapperGrammarAccess;

public class MapperParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MapperGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.bestsolution.objc.mapper.parser.antlr.internal.InternalMapperParser createParser(XtextTokenStream stream) {
		return new at.bestsolution.objc.mapper.parser.antlr.internal.InternalMapperParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PackageDeclaration";
	}
	
	public MapperGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MapperGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
