/*
* generated by Xtext
*/
package at.bestsolution.objc.mapper.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MapperAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("at/bestsolution/objc/mapper/parser/antlr/internal/InternalMapper.tokens");
	}
}
