/*
* generated by Xtext
*/
package at.bestsolution.objc.mapper;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MapperStandaloneSetup extends MapperStandaloneSetupGenerated{

	public static void doSetup() {
		new MapperStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

