/*
 * generated by Xtext
 */
package at.bestsolution.objc.mapper;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MapperRuntimeModule extends at.bestsolution.objc.mapper.AbstractMapperRuntimeModule {

}
