/*
 * generated by Xtext
 */
package at.bestsolution.objc.mapper.ui.contentassist

import at.bestsolution.objc.mapper.ui.contentassist.AbstractMapperProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MapperProposalProvider extends AbstractMapperProposalProvider {
}
