/*
 * generated by Xtext
 */
package at.bestsolution.objc.mapper.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import at.bestsolution.objc.mapper.ui.highlighting.ObjcHighlightingConfiguration;
import at.bestsolution.objc.mapper.ui.highlighting.ObjcSemanticHighlightingCalculator;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MapperUiModule extends at.bestsolution.objc.mapper.ui.AbstractMapperUiModule {
	public MapperUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		
		binder.bind(ISemanticHighlightingCalculator.class).to(ObjcSemanticHighlightingCalculator.class);
		binder.bind(IHighlightingConfiguration.class).to(ObjcHighlightingConfiguration.class);

	}
}
