/*
* generated by Xtext
*/
package at.bestsolution.objc.mapper;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MapperUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.bestsolution.objc.mapper.ui.internal.MapperActivator.getInstance().getInjector("at.bestsolution.objc.mapper.Mapper");
	}
	
}
